[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm@9",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["rm -rf apps/web/.next", "pnpm --filter web build"]

[start]
cmd = "pnpm --filter web start"
