[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm@9",
  "pnpm install --frozen-lockfile"
]
cacheDirectories = [".pnpm-store"]

[phases.build]
cmds = ["pnpm --filter admin build"]

[start]
cmd = "pnpm --filter admin start -p 3010"
