'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useAuthStore } from '@/store/auth.store';
import { COINS, COUNTRY_TO_COIN, CoinCode } from '@/store/wallet.store';

// Virtual account numbers (generated by fiat-bridge per user)
// In production these come from the API — here mocked by user ID hash
function getVirtualAccount(userId: string, country: string) {
  const seed = userId.slice(-4).padStart(4, '0');
  const accounts: Record<string, { methods: VirtualAccount[] }> = {
    GT: {
      methods: [
        {
          bank: 'Banrural',
          logo: '🏦',
          type: 'Transferencia bancaria',
          accountNumber: `5020-${seed}-GT-LEN`,
          reference: `LEN${seed.toUpperCase()}GT`,
          instructions: 'Realiza una transferencia a la cuenta Banrural de LEN e incluye tu referencia en el concepto.',
          min: 'Q 50',
          max: 'Q 25,000/día',
          time: '< 30 min (L-V hábil)',
        },
        {
          bank: 'BAM',
          logo: '🏛',
          type: 'Transferencia bancaria',
          accountNumber: `3010-${seed}-GT-LEN`,
          reference: `LEN${seed.toUpperCase()}GT`,
          instructions: 'Transfiere a la cuenta BAM de LEN. Tu referencia única identifica tu depósito.',
          min: 'Q 50',
          max: 'Q 25,000/día',
          time: '< 1 hora (L-V hábil)',
        },
      ],
    },
    MX: {
      methods: [
        {
          bank: 'SPEI (cualquier banco MX)',
          logo: '🇲🇽',
          type: 'CLABE interbancaria',
          accountNumber: `646180${seed}00000001`,
          reference: `LEN${seed.toUpperCase()}MX`,
          instructions: 'Usa esta CLABE en tu banca en línea para transferir MXN. El MEXCOIN aparece en minutos.',
          min: '$50 MXN',
          max: '$200,000 MXN/día',
          time: 'Inmediato (SPEI 24/7)',
        },
        {
          bank: 'OXXO Pay',
          logo: '🏪',
          type: 'Pago en tienda',
          accountNumber: `${seed}00OXXOLEN`,
          reference: `LEN${seed.toUpperCase()}`,
          instructions: 'Presenta este código en cualquier OXXO de México. Di "pago de servicio LEN".',
          min: '$20 MXN',
          max: '$10,000 MXN/día',
          time: '< 2 horas',
        },
      ],
    },
    HN: {
      methods: [
        {
          bank: 'Banco Atlántida',
          logo: '🏦',
          type: 'Transferencia bancaria',
          accountNumber: `3090-${seed}-HN-LEN`,
          reference: `LEN${seed.toUpperCase()}HN`,
          instructions: 'Transfiere lempiras a la cuenta de LEN en Atlántida con tu referencia única.',
          min: 'L 500',
          max: 'L 100,000/día',
          time: '< 1 hora (L-V hábil)',
        },
      ],
    },
  };
  return accounts[country] ?? accounts['GT'];
}

interface VirtualAccount {
  bank: string;
  logo: string;
  type: string;
  accountNumber: string;
  reference: string;
  instructions: string;
  min: string;
  max: string;
  time: string;
}

export default function AddMoneyPage() {
  const router = useRouter();
  const { user } = useAuthStore();
  const [selectedMethod, setSelectedMethod] = useState(0);
  const [copied, setCopied] = useState<string | null>(null);

  const country = user?.country ?? 'GT';
  const coin = COUNTRY_TO_COIN[country] ?? 'QUETZA';
  const coinMeta = COINS[coin];
  const accountData = getVirtualAccount(user?.id ?? 'demo', country);
  const method = accountData.methods[selectedMethod];

  function copy(text: string, label: string) {
    navigator.clipboard.writeText(text).catch(() => {});
    setCopied(label);
    setTimeout(() => setCopied(null), 2000);
  }

  return (
    <div className="max-w-md mx-auto px-4 pb-6">
      <div className="pt-5 mb-6">
        <button onClick={() => router.back()} className="btn-ghost mb-3 -ml-2 text-sm">
          ← Volver
        </button>
        <h1 className="text-2xl font-black text-len-dark">Agregar fondos</h1>
        <p className="text-gray-500 text-sm mt-1">
          Deposita {coinMeta.fiat} y recibe <span className="font-semibold text-len-purple">{coin}</span> al instante
        </p>
      </div>

      {/* Coin info */}
      <div className="card mb-4 flex items-center gap-3 py-4">
        <div className="w-12 h-12 bg-len-gradient rounded-2xl flex items-center justify-center text-2xl">
          {coinMeta.flag}
        </div>
        <div>
          <p className="font-bold text-len-dark">{coin} — {coinMeta.name}</p>
          <p className="text-sm text-gray-500">1 {coin} = 1 {coinMeta.fiat} · respaldado 1:1</p>
        </div>
        <div className="ml-auto bg-emerald-100 text-emerald-700 text-xs font-bold px-2.5 py-1 rounded-full">
          1:1
        </div>
      </div>

      {/* Method selector */}
      {accountData.methods.length > 1 && (
        <div className="flex gap-2 mb-4 overflow-x-auto scrollbar-hide">
          {accountData.methods.map((m, i) => (
            <button
              key={i}
              onClick={() => setSelectedMethod(i)}
              className={`flex-shrink-0 flex items-center gap-2 px-4 py-2 rounded-2xl border-2 text-sm font-semibold transition-all
                ${i === selectedMethod
                  ? 'border-len-purple bg-len-light text-len-purple'
                  : 'border-len-border bg-white text-gray-500 hover:border-len-violet'}`}
            >
              <span>{m.logo}</span>
              <span>{m.bank}</span>
            </button>
          ))}
        </div>
      )}

      {/* Account details */}
      <div className="card space-y-4">
        <div>
          <p className="text-xs text-gray-400 uppercase tracking-widest font-semibold mb-1">{method.type}</p>
          <p className="text-lg font-bold text-len-dark">{method.bank}</p>
        </div>

        {/* Account number */}
        <div className="bg-len-light rounded-2xl p-4">
          <div className="flex items-center justify-between mb-1">
            <p className="text-xs text-gray-500 font-medium">Número de cuenta / CLABE</p>
            <button
              onClick={() => copy(method.accountNumber, 'cuenta')}
              className="text-xs text-len-purple font-semibold"
            >
              {copied === 'cuenta' ? '✓ Copiado' : 'Copiar'}
            </button>
          </div>
          <p className="font-mono text-len-dark font-bold text-lg tracking-wider break-all">
            {method.accountNumber}
          </p>
        </div>

        {/* Reference */}
        <div className="bg-amber-50 rounded-2xl p-4 border border-amber-200">
          <div className="flex items-center justify-between mb-1">
            <p className="text-xs text-amber-700 font-semibold">⚠ Referencia obligatoria</p>
            <button
              onClick={() => copy(method.reference, 'ref')}
              className="text-xs text-len-purple font-semibold"
            >
              {copied === 'ref' ? '✓ Copiado' : 'Copiar'}
            </button>
          </div>
          <p className="font-mono text-amber-900 font-black text-xl tracking-widest">
            {method.reference}
          </p>
          <p className="text-xs text-amber-600 mt-1">
            Incluye esta referencia en el concepto o descripción de tu transferencia.
            Sin ella, el depósito no se acredita automáticamente.
          </p>
        </div>

        {/* Instructions */}
        <p className="text-sm text-gray-600 leading-relaxed">{method.instructions}</p>

        {/* Meta info */}
        <div className="grid grid-cols-3 gap-2 pt-2 border-t border-len-border">
          {[
            { label: 'Mínimo', value: method.min },
            { label: 'Límite diario', value: method.max },
            { label: 'Tiempo', value: method.time },
          ].map(item => (
            <div key={item.label} className="text-center">
              <p className="text-xs text-gray-400">{item.label}</p>
              <p className="text-xs font-bold text-len-dark mt-0.5">{item.value}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Also receive from other LEN users */}
      <div className="mt-4 card bg-len-light border-len-border py-4">
        <p className="text-sm font-semibold text-len-dark mb-1">💸 ¿Otro usuario de LEN te envía?</p>
        <p className="text-xs text-gray-500 mb-3">
          Puedes recibir cualquier moneda LEN (QUETZA, MEXCOIN, LEMPI…) directamente en tu wallet.
          No necesitas hacer nada — solo comparte tu número de teléfono o código QR.
        </p>
        <button
          onClick={() => router.push('/receive')}
          className="btn-secondary w-full text-sm py-2.5"
        >
          Ver mi QR para recibir →
        </button>
      </div>
    </div>
  );
}
